# Generated by Django 3.0.7 on 2020-07-11 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_auto_20200711_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 16, 24, 14, 773437)),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.TextField(max_length=160),
        ),
    ]
