# Generated by Django 3.0.7 on 2020-07-11 19:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_auto_20200711_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='date',
        ),
        migrations.AddField(
            model_name='new',
            name='city',
            field=models.TextField(default='Crespo', max_length=80),
        ),
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AddField(
            model_name='new',
            name='new_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 11, 16, 40, 3, 201171)),
        ),
        migrations.AddField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 16, 40, 3, 201171)),
        ),
        migrations.AlterField(
            model_name='new',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ManyToManyField(related_name='new_category', to='newspaper.Category'),
        ),
    ]
