# Generated by Django 3.0.7 on 2020-07-11 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0007_auto_20200711_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_category', to='newspaper.Category'),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 11, 16, 54, 19, 771484)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 16, 54, 19, 771484)),
        ),
    ]
