# Generated by Django 3.0.7 on 2020-07-11 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0009_auto_20200711_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 11, 17, 2, 57, 904296)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 17, 2, 57, 904296)),
        ),
    ]
