# Generated by Django 3.0.7 on 2020-07-12 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0010_auto_20200711_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(default='News', max_length=60),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 12, 12, 13, 29, 167968)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 12, 13, 29, 167968)),
        ),
    ]
