# Generated by Django 3.0.7 on 2020-07-12 19:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0011_auto_20200712_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 12, 16, 27, 31, 124023)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 16, 27, 31, 124023)),
        ),
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_new', to='newspaper.New')),
            ],
        ),
        migrations.CreateModel(
            name='Primary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_new', to='newspaper.New')),
            ],
        ),
        migrations.CreateModel(
            name='Oldnew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_new', to='newspaper.New')),
            ],
        ),
    ]
