# Generated by Django 3.0.7 on 2020-07-12 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0012_auto_20200712_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 12, 16, 28, 42, 458984)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 16, 28, 42, 458984)),
        ),
        migrations.RemoveField(
            model_name='oldnew',
            name='old_new',
        ),
        migrations.AddField(
            model_name='oldnew',
            name='old_new',
            field=models.ManyToManyField(related_name='old_new', to='newspaper.New'),
        ),
        migrations.RemoveField(
            model_name='secondary',
            name='secondary_new',
        ),
        migrations.AddField(
            model_name='secondary',
            name='secondary_new',
            field=models.ManyToManyField(related_name='secondary_new', to='newspaper.New'),
        ),
    ]
