# Generated by Django 3.0.7 on 2020-07-12 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0013_auto_20200712_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 12, 16, 29, 40, 587890)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 16, 29, 40, 587890)),
        ),
    ]
