# Generated by Django 3.0.7 on 2020-07-12 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0014_auto_20200712_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primary',
            name='primary_new',
        ),
        migrations.RemoveField(
            model_name='secondary',
            name='secondary_new',
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 12, 16, 33, 43, 450195)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 16, 33, 43, 450195)),
        ),
        migrations.DeleteModel(
            name='Oldnew',
        ),
        migrations.DeleteModel(
            name='Primary',
        ),
        migrations.DeleteModel(
            name='Secondary',
        ),
    ]
