# Generated by Django 3.0.7 on 2020-07-12 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0015_auto_20200712_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 12, 16, 33, 48, 448242)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 16, 33, 48, 448242)),
        ),
    ]
