# Generated by Django 3.0.7 on 2020-07-12 22:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newspaper.models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0017_auto_20200712_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 12, 19, 58, 33, 230468)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 19, 58, 33, 230468)),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=newspaper.models.get_image_path)),
                ('new_date', models.DateField(blank=True, default=datetime.datetime(2020, 7, 12, 19, 58, 33, 231445))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
