# Generated by Django 3.0.7 on 2020-07-15 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0019_auto_20200712_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 15, 13, 15, 4, 5859)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 15, 13, 15, 4, 3906)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 13, 15, 4, 3906)),
        ),
    ]
