# Generated by Django 3.0.7 on 2020-07-15 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0022_auto_20200715_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='description',
        ),
        migrations.AddField(
            model_name='new',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 15, 14, 29, 46, 539062)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 15, 14, 29, 46, 537109)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 14, 29, 46, 537109)),
        ),
    ]
