# Generated by Django 3.0.7 on 2020-07-15 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0023_auto_20200715_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 15, 14, 30, 34, 478515)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 15, 14, 30, 34, 476562)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 14, 30, 34, 476562)),
        ),
    ]
