# Generated by Django 3.0.7 on 2020-07-15 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0024_auto_20200715_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 15, 15, 0, 15, 245117)),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 15, 15, 0, 15, 244140)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 15, 0, 15, 244140)),
        ),
    ]
