# Generated by Django 3.0.7 on 2020-07-15 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0025_auto_20200715_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 15, 15, 1, 28, 389648)),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 15, 15, 1, 28, 386718)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 15, 1, 28, 386718)),
        ),
    ]
