# Generated by Django 3.0.7 on 2020-07-17 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0026_auto_20200715_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 7, 17, 13, 16, 21, 102539))),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 17, 13, 16, 21, 102539)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 17, 13, 16, 21, 100585)),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_date_upload',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 13, 16, 21, 100585)),
        ),
    ]
